/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restaurant;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Administrator
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
     private DefaultTableModel model;
   String columns[]={"ID","Item Name","Category","Price(₹)","Status"};
      

    public Menu() {
        initComponents();
        new CreateTable();
       
        model = new DefaultTableModel(columns,0);
         Mtable.setModel(model);
         
                loadTable();
                setupTwoPanelLayout();
    }public void loadTable() {

        model.setRowCount(0);

        try {
            Connection con = DBConnection.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT ID, Item, Category,Price,Status FROM Menu ORDER BY ID");

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("ID"),
                    rs.getString("Item"),
                    rs.getString("Category"),
                    rs.getInt("Price"),
                    rs.getString("Status")
                });
            }

            rs.close();
            st.close();
            con.close();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error loading data: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Mtable = new javax.swing.JTable();
        panel1 = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();
        Item = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Price = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        Status = new javax.swing.JComboBox<>();
        Category = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setText("Restaurant JS-Menu");

        Mtable.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Mtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Mtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Mtable);

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel3.setText("Item Name:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel4.setText("Category:");

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel5.setText("Price:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel6.setText("Status:");

        Add.setBackground(new java.awt.Color(255, 0, 0));
        Add.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("Add");
        Add.addActionListener(this::AddActionPerformed);

        Update.setBackground(new java.awt.Color(0, 204, 0));
        Update.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Update.setForeground(new java.awt.Color(255, 255, 255));
        Update.setText("Update");
        Update.addActionListener(this::UpdateActionPerformed);

        Delete.setBackground(new java.awt.Color(255, 0, 0));
        Delete.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Delete");
        Delete.addActionListener(this::DeleteActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setText("ID:");

        Status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));

        Category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "\uD83C\uDF55Pizza", "\uD83C\uDF54Burger", "\uD83C\uDF5FSnacks", "\uD83C\uDF5DPasta", "\uD83C\uDF70Desserts", "\u2615Beverages", "\uD83C\uDF79Drinks" }));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Category, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Item, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addComponent(Price))
                .addGap(23, 23, 23))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(Add)
                .addGap(39, 39, 39)
                .addComponent(Update)
                .addGap(35, 35, 35)
                .addComponent(Delete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add)
                    .addComponent(Update)
                    .addComponent(Delete))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(406, Short.MAX_VALUE))
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
          try {
             String item = Item.getText().trim();
             String category=Category.getSelectedItem().toString().trim();
             int price = Integer.parseInt(Price.getText().trim());
             String status=Status.getSelectedItem().toString().trim();
           if (item.isEmpty()) {
                 javax.swing.JOptionPane.showMessageDialog(this, "Item cannot be empty.");
                 return;
             }
            Connection con = DBConnection.getConnection();
            PreparedStatement ps = con.prepareStatement(
                "INSERT INTO Menu(Item, Category,Price, Status) VALUES (?, ?,?,?)");
            ps.setString(1, item);
            ps.setString(2,category);
            ps.setInt(3, price);
             ps.setString(4, status);
             
            ps.executeUpdate();
            ps.close();
            con.close();

            loadTable();

            clearFields();

        }catch (Exception e) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error adding record: " + e.getMessage());

        }
    }//GEN-LAST:event_AddActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
         int row = Mtable.getSelectedRow();

        if (row == -1) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Select a row first.");

            return;
        }
         try {
             String item = Item.getText().trim();
             String category=Category.getSelectedItem().toString().trim();
             int price = Integer.parseInt(Price.getText().trim());
             String status=Status.getSelectedItem().toString().trim();
              if (item.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Item cannot be empty.");
                return;
            }
            int selectedID = (int) model.getValueAt(row, 0);
            Connection con = DBConnection.getConnection();
            PreparedStatement ps = con.prepareStatement(
                "UPDATE Menu SET Item = ?, Category= ?,Price=?,Status=? WHERE ID = ?");
            ps.setString(1, item);
            ps.setString(2,category);
            ps.setInt(3, price);
            ps.setString(4, status);
            ps.setInt(5,selectedID);
            int rows = ps.executeUpdate();
            ps.close();
            con.close();

            if (rows == 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "No record found to update.");
            } else {
                loadTable();
                clearFields();
            }

        } catch (Exception e) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error updating record: " + e.getMessage());

        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
           int row = Mtable.getSelectedRow();

        if (row == -1) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Select a row first.");

            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this record?",
                "Confirm Delete", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        try {

            // Use the roll_no of the selected row to identify the record
            int selectedID = (int) model.getValueAt(row, 0);

            Connection con = DBConnection.getConnection();
            PreparedStatement ps = con.prepareStatement(
                "DELETE FROM Menu WHERE ID = ?");
            ps.setInt(1, selectedID);
            ps.executeUpdate();
        loadTable();

        clearFields();
    }                                      
catch (Exception e) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error deleting record: " + e.getMessage());

        } 
    }//GEN-LAST:event_DeleteActionPerformed

    private void MtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MtableMouseClicked
        // TODO add your handling code here:
         int row = Mtable.getSelectedRow();

        if (row == -1) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Select a row first.");

            return;
        }
          Object selectedID = model.getValueAt(row, 0);
        ID.setText(String.valueOf(selectedID));
        String item = (String) model.getValueAt(row, 1);
        Item.setText(item);
         String category = (String) model.getValueAt(row, 2);
     Category.setSelectedItem(category);
        Object price= model.getValueAt(row, 3);
        Price.setText(String.valueOf(price));
        String status= (String) model.getValueAt(row, 4);
        Status.setSelectedItem(status);
    }//GEN-LAST:event_MtableMouseClicked
public void clearFields() {
        ID.setText("");
        Item.setText("");
        
        Price.setText("");
       

    }

    private void setupTwoPanelLayout() {
        this.setLayout(new java.awt.BorderLayout());
        this.removeAll();

        javax.swing.JPanel topPanel = new javax.swing.JPanel(new java.awt.BorderLayout());
        topPanel.setBackground(new java.awt.Color(0, 0, 51));
        jLabel1.setForeground(java.awt.Color.WHITE);
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        topPanel.add(jLabel1, java.awt.BorderLayout.WEST);
        this.add(topPanel, java.awt.BorderLayout.NORTH);

        javax.swing.JSplitPane splitPane = new javax.swing.JSplitPane(javax.swing.JSplitPane.HORIZONTAL_SPLIT, jScrollPane1, panel1);
        splitPane.setDividerLocation(500);
        splitPane.setResizeWeight(0.6);
        this.add(splitPane, java.awt.BorderLayout.CENTER);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JComboBox<String> Category;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Item;
    private javax.swing.JTable Mtable;
    private javax.swing.JTextField Price;
    private javax.swing.JComboBox<String> Status;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
