    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restaurant;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Administrator
 */
public class Staff extends javax.swing.JPanel {

    /**
     * Creates new form Staff
     */
     private DefaultTableModel model;
   String columns[]={"ID","Name","Phone Number","Role","Salary(₹)"};
  
    public Staff() {
        initComponents();
       new CreateTable();
        model = new DefaultTableModel(columns,0);
        Stable.setModel(model);
        
        loadTable();
        setupTwoPanelLayout();
    }
     public void loadTable() {

        model.setRowCount(0);

        try {
            Connection con = DBConnection.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT ID, Name, Phone,Role,Salary FROM Staff ORDER BY ID");

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("ID"),
                    rs.getString("Name"),
                    rs.getLong("Phone"),
                    rs.getString("Role"),
                    rs.getInt("Salary")
                });
            }

            rs.close();
            st.close();
            con.close();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error loading data: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Stable = new javax.swing.JTable();
        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Phone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Role = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        Salary = new javax.swing.JTextField();
        Addstaff = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        Update = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel2.setText("Staff Management");

        Stable.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Stable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Stable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Stable);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel3.setText("Phone:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel4.setText("Role:");

        Role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Server", "Busser", "Chef" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel5.setText("Salary:");

        Addstaff.setBackground(new java.awt.Color(0, 153, 102));
        Addstaff.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        Addstaff.setForeground(new java.awt.Color(255, 255, 255));
        Addstaff.setText("Add ");
        Addstaff.addActionListener(this::AddstaffActionPerformed);

        Delete.setBackground(new java.awt.Color(255, 51, 51));
        Delete.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Delete Staff");
        Delete.addActionListener(this::DeleteActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel6.setText("ID:");

        Update.setBackground(new java.awt.Color(0, 153, 0));
        Update.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Update.setForeground(new java.awt.Color(255, 255, 255));
        Update.setText("Update");
        Update.addActionListener(this::UpdateActionPerformed);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Role, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(Addstaff, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(Update)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addstaff)
                    .addComponent(Delete)
                    .addComponent(Update))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
@SuppressWarnings("unchecked")
    private void AddstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddstaffActionPerformed
        // TODO add your handling code here:
        try {
            String name = Name.getText().trim();
            long phone  = Long.parseLong(Phone.getText().trim());
            String role=Role.getSelectedItem().toString().trim();
            int salary = Integer.parseInt(Salary.getText().trim());
             
            if (name.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Name cannot be empty.");
                return;
            }

            Connection con = DBConnection.getConnection();
            PreparedStatement ps = con.prepareStatement(
                "INSERT INTO Staff (Name, Phone, Role, Salary) VALUES (?, ?, ?, ?)");
            ps.setString(1, name);
            ps.setLong(2, phone);
            ps.setString(3, role);
            ps.setInt(4, salary);
            ps.executeUpdate();
            ps.close();
            con.close();


            loadTable();

            clearFields();

        }  catch (Exception e) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error adding record: " + e.getMessage());

        }
    }//GEN-LAST:event_AddstaffActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
          int row = Stable.getSelectedRow();

        if (row == -1) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Select a row first.");

            return;
        }
 int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this record?",
                "Confirm Delete", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        try {

            // Use the roll_no of the selected row to identify the record
            int selectedID = (int) model.getValueAt(row, 0);

            Connection con = DBConnection.getConnection();
            PreparedStatement ps = con.prepareStatement(
                "DELETE FROM Staff WHERE ID = ?");
            ps.setInt(1, selectedID);
            ps.executeUpdate();
            ps.close();
            con.close();
       

        loadTable();
        clearFields();
    }//GEN-LAST:event_DeleteActionPerformed
catch (Exception e) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error deleting record: " + e.getMessage());

        }
    }  
    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
         int row = Stable.getSelectedRow();

        if (row == -1) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Select a row first.");

            return;
        }
          try {
            String name = Name.getText().trim();
            long phone  = Long.parseLong(Phone.getText().trim());
            String role=Role.getSelectedItem().toString().trim();
            int salary = Integer.parseInt(Salary.getText().trim());
             
            if (name.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Name cannot be empty.");
                return;
            }

           int selectedID = (int) model.getValueAt(row, 0);
            Connection con = DBConnection.getConnection();
            PreparedStatement ps = con.prepareStatement(
                "UPDATE Staff SET Name= ?, Phone= ?,Role=?,Salary=? WHERE ID = ?");
            ps.setString(1, name);
            ps.setLong(2, phone);
             ps.setString(3, role);
              ps.setInt(4, salary);
            ps.setInt(5,selectedID);
            int rows = ps.executeUpdate();
            ps.close();
            con.close();
            if (rows == 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "No record found to update.");
            } else {
                loadTable();
                clearFields();
            }

        } catch (Exception e) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error updating record: " + e.getMessage());

        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void StableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StableMouseClicked
        // TODO add your handling code here:
        
          int row = Stable.getSelectedRow();

        if (row == -1) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Select a row first.");

            return;
        }
        
        Object selectedID = model.getValueAt(row, 0);
        ID.setText(String.valueOf(selectedID));
        String name = (String) model.getValueAt(row, 1);
        Name.setText(name);
         String role = (String) model.getValueAt(row, 3);
      Role.setSelectedItem(role);
        Object phone = model.getValueAt(row, 2);
        Phone.setText(String.valueOf(phone));
        Object salary= model.getValueAt(row, 4);
        Salary.setText(String.valueOf(salary));
    }//GEN-LAST:event_StableMouseClicked
                                
 public void clearFields() {
        ID.setText("");
        Salary.setText("");
        Name.setText("");
        Phone.setText("");
    }

    private void setupTwoPanelLayout() {
        this.setLayout(new java.awt.BorderLayout());
        this.removeAll();

        javax.swing.JPanel topPanel = new javax.swing.JPanel(new java.awt.BorderLayout());
        topPanel.setBackground(new java.awt.Color(0, 0, 51));
        jLabel2.setForeground(java.awt.Color.WHITE);
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        topPanel.add(jLabel2, java.awt.BorderLayout.WEST);
        this.add(topPanel, java.awt.BorderLayout.NORTH);

        javax.swing.JSplitPane splitPane = new javax.swing.JSplitPane(javax.swing.JSplitPane.HORIZONTAL_SPLIT, jScrollPane1, panel1);
        splitPane.setDividerLocation(500);
        splitPane.setResizeWeight(0.6);
        this.add(splitPane, java.awt.BorderLayout.CENTER);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addstaff;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Phone;
    private javax.swing.JComboBox<String> Role;
    private javax.swing.JTextField Salary;
    private javax.swing.JTable Stable;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables

    
}
